'use client';

import { useState } from 'react';
import { LanguageToggle } from '@/components/ui/LanguageToggle';
import type { Language } from '@/lib/i18n';

export default function TermsPage() {
  const [lang, setLang] = useState<Language>('en');

  const content = {
    title: { en: 'Terms of Service', zh: '服务条款' },
    lastUpdated: { en: 'Last updated: May 2026', zh: '最后更新：2026年5月' },
    sections: [
      {
        title: { en: '1. Educational Purpose', zh: '1. 教育目的' },
        body: {
          en: 'Cultural Compass is an educational game designed to help Chinese adoptees learn about Chinese social etiquette and cultural norms. The in-game NPCs (aunties and uncles) simulate social interactions for learning purposes only. No professional, legal, or psychological advice is provided.',
          zh: '文化指南是一款教育游戏，旨在帮助华裔被收养者了解中国社交礼仪和文化规范。游戏中的NPC（阿姨和叔叔）仅为学习目的模拟社交互动。不提供任何专业、法律或心理建议。',
        },
      },
      {
        title: { en: '2. AI-Generated Content', zh: '2. AI生成内容' },
        body: {
          en: 'Conversations in this game are generated by an AI language model (DeepSeek). While the AI is guided by carefully crafted cultural prompts, it may occasionally produce unexpected or inaccurate content. NPC dialogue represents cultural patterns and norms, not absolute rules — individual experiences in Chinese culture vary widely.',
          zh: '本游戏中的对话由AI语言模型（DeepSeek）生成。虽然AI受精心设计的文化提示引导，但偶尔可能产生意外或不准确的内容。NPC对话代表文化模式和规范，而非绝对规则——个人在中国文化中的体验差异很大。',
        },
      },
      {
        title: { en: '3. No Personal Information', zh: '3. 请勿分享个人信息' },
        body: {
          en: 'Do not share personal information (real names, contact details, addresses, financial information) in your conversations with the AI. The game is designed for fictional roleplay scenarios — use it as a safe space to practice cultural interactions without revealing your real identity.',
          zh: '请勿在与AI的对话中分享个人信息（真实姓名、联系方式、地址、财务信息）。本游戏专为虚构角色扮演场景设计——请将其作为练习文化互动的安全空间，无需透露您的真实身份。',
        },
      },
      {
        title: { en: '4. Acceptable Use', zh: '4. 可接受的使用方式' },
        body: {
          en: 'You agree to use Cultural Compass for its intended educational purpose. Any attempt to manipulate the AI into generating harmful, illegal, or inappropriate content is prohibited. We reserve the right to filter or block content that violates these terms.',
          zh: '您同意将文化指南用于其预期的教育目的。禁止任何试图操纵AI生成有害、非法或不当内容的行为。我们保留过滤或屏蔽违反这些条款的内容的权利。',
        },
      },
      {
        title: { en: '5. No Warranty', zh: '5. 免责声明' },
        body: {
          en: 'Cultural Compass is provided "as is" without warranties of any kind. The game may be unavailable due to maintenance, API provider outages, or other technical issues. We are not responsible for any emotional discomfort that may arise from exploring cultural themes — please take breaks as needed and remember this is a learning journey, not a test.',
          zh: '文化指南按"原样"提供，不作任何形式的保证。游戏可能因维护、API服务商故障或其他技术问题而不可用。我们不对探索文化主题可能引起的任何情感不适负责——请根据需要休息，记住这是一段学习旅程，而非考试。',
        },
      },
      {
        title: { en: '6. Changes to Terms', zh: '6. 条款变更' },
        body: {
          en: 'We may update these terms as the game evolves. Significant changes will be noted in the game\'s update log. Continued use of Cultural Compass after changes constitutes acceptance of the updated terms.',
          zh: '我们可能随着游戏的发展而更新这些条款。重大变更将在游戏更新日志中注明。在变更后继续使用文化指南即表示接受更新后的条款。',
        },
      },
    ],
  };

  return (
    <div className="min-h-screen bg-stone-100">
      <div className="max-w-2xl mx-auto px-4 py-12">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-2xl font-bold text-stone-900">{content.title[lang]}</h1>
          <LanguageToggle lang={lang} onToggle={setLang} />
        </div>
        <p className="text-sm text-stone-400 mb-8">{content.lastUpdated[lang]}</p>
        {content.sections.map((section, i) => (
          <div key={i} className="mb-8">
            <h2 className="text-lg font-semibold text-stone-800 mb-3">{section.title[lang]}</h2>
            <p className="text-stone-600 leading-relaxed">{section.body[lang]}</p>
          </div>
        ))}
        <div className="mt-12 pt-8 border-t border-stone-200 flex gap-6">
          <a href="/" className="text-sm text-amber-600 hover:text-amber-700 transition-colors">
            {lang === 'en' ? '← Back to Cultural Compass' : '← 返回文化指南'}
          </a>
          <a href="/privacy" className="text-sm text-amber-600 hover:text-amber-700 transition-colors">
            {lang === 'en' ? 'Privacy Policy' : '隐私政策'}
          </a>
        </div>
      </div>
    </div>
  );
}
